### ISSUE TITLE
Running speed 

### ISSUE THREAD

**Issue by ZPHuang-ACM** [quadprog/quadprog#18]
Hi,

I wonder what's the running speed in comparison to the C++ counterpart QuadProgPP?

**Comment by rmcgibbo** [comment]
I have absolutely no idea. If you find it, it might be useful if you could post a link to your results here.

**Comment by preeyan** [comment]
@ZPHuang-ACM Quadprog is considered to be a competitive solver for dense problems. You may find it interesting to read the benchmarks at https://github.com/stephane-caron/qpsolvers#performances .
