### ISSUE TITLE
Inconsistent equality lagrange multipliers in quadprog

### ISSUE THREAD

**Issue by feslima** [quadprog/quadprog#2]
Hello guys.

I'm having quite a headache with the equality constraints lagrange multipliers coming from the quadprog solver. The example to reproduce the issue is as follows:

```
import numpy as np
from quadprog import solve_qp
G = np.eye(5)
a = - np.array([-0.73727161, -0.75526241, -0.04741426,  0.11260887,  0.11260887])
C = -np.array([
[-3.6,   3.4,   3.8,  -1.6,  -1.6 ],
[ 0.,    1.9,   1.7,   4.,    4.  ],
[ 9.72,  8.67,  0.,    0.,    0.  ],
])
b = np.array([1.02, 0.03, 0.081])
meq = b.size
sol = solve_qp(G, a, C=C.T, b=b, meq=meq)
```
I compared against quadprog's routine from MATLAB and qp from Octave. The x values are ok, however, the sign of the Lagrange multipliers are not. I tried to find any clues in the article cited, but got nothing. This behavior doesn't happen for the inequality lagrange multipliers, only for the equality ones.

The correct solution is:
`x = sol[0] = [ 0.07313507 -0.09133482 -0.08677699  0.03638213  0.03638213]` and the expected Lagrange values are:
`[-0.0440876  0.01961271 -0.08465554]` (Octave's qp routine)
`[0.0440876  -0.01961271 0.08465554]` (MATLAB's quadprog routine. The sign are inverted because the QP constraint structure in MATLAB is C^T * x <= 0, and Octave is C^T * x >= 0)

The values I get are:
`[0.0440876  0.01961271 0.08465554]` (Python's quadprog)

Any help or insight is really appreciated.

**Comment by rmcgibbo** [comment]
I’m sorry, I really have no idea what might be responsible for the discrepancy. It’s possible that there’s a bug in the Python on wrapper, or that there’s a deeper problem in the wrapped FORTRAN code. I’m sorry I can’t help more. Best of luck, Robert.

**Comment by feslima** [comment]
Thanks for the response. I've been using an workaround. So far there wasn't any problems.

After going back to the fundamentals of QP, I've found this on Nocedal's Numerical Optimization book (2006):
![image](https://user-images.githubusercontent.com/26683783/57783415-75b6ce80-7704-11e9-8f25-43e49c8e643d.png)

The quadprog solver returns the indexes of the active constraints at the solution (these constraints are the equalities plus the inequalities, if they are indeed active at the solution). So I just solve the system of equations described by equation 16.37a.

For the problem I cited above, the solution in python would be:

```
import numpy as np
import scipy as sp
from quadprog import solve_qp
G = np.eye(5)
a = - np.array([-0.73727161, -0.75526241, -0.04741426,  0.11260887,  0.11260887])
C = -np.array([
[-3.6,   3.4,   3.8,  -1.6,  -1.6 ],
[ 0.,    1.9,   1.7,   4.,    4.  ],
[ 9.72,  8.67,  0.,    0.,    0.  ],
])
b = np.array([1.02, 0.03, 0.081])
meq = b.size
sol = solve_qp(G, a, C=C.T, b=b, meq=meq)

# backsolving to get equality lagrange multipliers

# the -1 is to change from fortran indexing to python/numpy indexing
active_set_idx = np.sort(sol[5] - 1)  
lmbd_active_set = sp.linalg.lstsq(C[:, active_set_idx], G @ sol[0] + a)[0]
lmbd_eq = lmbd_active_set[:meq]  # this is to get equality multipliers only
```
This gives the correct solution.

**Comment by preeyan** [comment]
Thanks for the feedback @feslima .

The underlying algorithm treated equality constraints in such a way that although the correct solution would be found, the Lagrange multipliers would always have a positive sign regardless of the correct value.

I have reimplemented the treatment of equality constraints so that the correct Lagrange multipliers should now be returned.
