### ISSUE TITLE
Direct Usage in C

### ISSUE THREAD

**Issue by feiyuxiaoThu** [quadprog/quadprog#33]
I found the solver was based on pure C, so I am wondering whether it is posssible to use this solver in C form?  Thanks for your kind reply.

**Comment by preeyan** [comment]
Hi @feiyuxiaoThu - it is indeed possible to use the solver directly in C form without going through the Python binding.

To achieve this you can simply use the C source files directly. At present these are the three *.c files in the quadprog directory of this repository. Do bear in mind the licence (https://github.com/quadprog/quadprog/blob/master/LICENSE).

Please post back if anything is unclear.
